name: Automatic release

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

env:
  DOCKER_REGISTRY: jodlidev
  DOCKER_IMAGE_NAME: scidataseal

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Create tag
        uses: butlerlogic/action-autotag@1.1.2
        id: autotag
        env:
            GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        with:
            strategy: package
            tag_prefix: "v"
      
      - name: Install Dependencies
        if: ${{steps.autotag.outputs.tagcreated == 'yes'}}
        run: npm install
      
      - name: Build for production
        if: ${{steps.autotag.outputs.tagcreated == 'yes'}}
        run: npm run prepare_dist & webpack --config webpack_config/build.production.js
      
      - name: Log in to Docker Hub
        if: ${{steps.autotag.outputs.tagcreated == 'yes'}}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Extract metadata (tags, labels) for Docker
        if: ${{steps.autotag.outputs.tagcreated == 'yes'}}
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_IMAGE_NAME}}
      
      - name: Build and push Docker image
        if: ${{steps.autotag.outputs.tagcreated == 'yes'}}
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jodlidev/scidataseal:${{steps.autotag.outputs.tagname}}
            jodlidev/scidataseal:latest
          labels: ${{steps.meta.outputs.labels}}
