export type Endpoints
	= "/initialize"
	| "/editBlockchainAccount"
	| "/editQuestionnaire"
	| "/generateRandomString"
	| "/getBlockchainAccount"
	| "/getNewDenotation"
	| "/getQuestionnaire"
	| "/listBlockchainAccounts"
	| "/listQuestionnaireData"
	| "/listQuestionnaires"
	| "/login"
	| "/saveData"
	| "/setQuestionnaireColumns"
	| "/solana";
